eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 8090
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/productos/**
        
      - id: ITEM-SERVICE
        uri: lb://ITEM-SERVICE
        predicates:
        - Path=/items/** 
